import Image from "next/image";
import TitleSection from "../components/TitleSection";
import InterviewCards from "../components/Interview-cards/InterviewCards";

export default function Home() {
  return (
    <>
      <section>
        <div className="flex flex-col md:flex-row-reverse gap-7 justify-between">
          <div className="rounded-xl border py-8 shadow-sm bg-[url('/abstract-design.svg')] bg-cover flex justify-center items-center max-w-3xl">
            <Image
              src="/neural-network.png"
              height={669}
              width={755}
              alt="neural network"
              className="w-1/2 md:w-3/4"
            />
          </div>
          <TitleSection
            title="Practice Interviews, Land Your Dream Job"
            subtitle="Build confidence through practice. Experience real interview scenarios and refine your answers before the big day."
            button={true}
          />
        </div>
      </section>
      <section className="mt-10">
        <TitleSection title="Your interviews" subtitle="Your interview history"/>
        <InterviewCards />
      </section>
      <section className="mt-10 md:mt-20">
        <TitleSection title="Take an existing interview" subtitle="Take interviews generated by others"/>
        <InterviewCards />
      </section>
    </>
  );
}
